module.exports = {
  googleClientID: '',
  googleClientSecret: '',
  coinbaseClientID: '',
  coinbaseClientSecret: '',
  coinbaseAPISecret: '',
  coinbaseAPIKey: '',
  mongoURI: '',
  cookieKey: '',
  coinbaseProSecret: '',  
  coinbaseProKey: '',
  coinbaseProPassphrase: '',
  coinbaseKey: '',
  coinbaseSecret: '',
}
